configType = "custom"
l1ChainID = 11155111
fundDevAccounts = false
l1ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-b112b16f8939fbb732c0693de3d3bd1e8e3e2f0771f91d5ab300a6c9b7b1af73.tar.gz"
l2ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-b112b16f8939fbb732c0693de3d3bd1e8e3e2f0771f91d5ab300a6c9b7b1af73.tar.gz"

[superchainRoles]
  SuperchainProxyAdminOwner = "0xe934dc97e347c6acef74364b50125bb8689c40ff"
  SuperchainGuardian = "0xe934dc97e347c6acef74364b50125bb8689c40ff"
  ProtocolVersionsOwner = "0xe934dc97e347c6acef74364b50125bb8689c40ff"
  Challenger = "0xf6015e1850d6622921a647a76ffd892ba6870b75"

[[chains]]
  id = "0x00000000000000000000000000000000000000000000000000000000190a85e2"
  baseFeeVaultRecipient = "0xf1a0033a47418b14ca73becd25669757bcf60de8"
  l1FeeVaultRecipient = "0x320d7ad3f12aec527170ec23297b3196ee32e8f4"
  sequencerFeeVaultRecipient = "0xee7d049e5f573a08bb5a358fcefb3d4af992fdcb"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  gasLimit = 60000000
  operatorFeeScalar = 0
  operatorFeeConstant = 0
  minBaseFee = 0
  daFootprintGasScalar = 0
  [chains.roles]
    l1ProxyAdminOwner = "0xe934dc97e347c6acef74364b50125bb8689c40ff"
    l2ProxyAdminOwner = "0x079b83b81617b9e3bdbd8bc128d4faa7e7f44d04"
    systemConfigOwner = "0x3dbd1346f226189439cddb6485f503d174f8bb34"
    unsafeBlockSigner = "0x83e31a4d1f993b07222d1519d6a2c9d38328a066"
    batcher = "0x0d74b00f88dfb85cb042e6be3fb6fe72797e3fe7"
    proposer = "0x87be7931c05b3f0b780557af07fbbbda741a0075"
    challenger = "0x94e6f45d675105507f3297fe64fe6cb59eaaf820"
  [chains.deployOverrides]

[globalDeployOverrides]
  disputeGameFinalityDelaySeconds = 300
  l2GenesisJovianTimeOffset = "0x0"

