configType = "custom"
opDeployerVersion = "untagged-d6aa14e9-1765836611"
l1ChainID = 11155111
fundDevAccounts = false
l1ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-ba6ee9bdfcb5b15d00a1727800632dc05cfcb7d90d7a01b2a20ac7308ea4c8d4.tar.zst"
l2ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-ba6ee9bdfcb5b15d00a1727800632dc05cfcb7d90d7a01b2a20ac7308ea4c8d4.tar.zst"

[superchainRoles]
  SuperchainProxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  SuperchainGuardian = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  ProtocolVersionsOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  Challenger = "0xf6015e1850d6622921a647a76ffd892ba6870b75"

[[chains]]
  id = "0x00000000000000000000000000000000000000000000000000000000190a85e1"
  baseFeeVaultRecipient = "0xc4e34d46971754a9e3191f57cc5429c35d60a340"
  l1FeeVaultRecipient = "0x039449b19550e3582a5a6a69dede8bd4ead2381e"
  sequencerFeeVaultRecipient = "0x7e31e1eafb4d1486c05743e5c496cb5042843d7a"
  operatorFeeVaultRecipient = "0x62db3472be0eb8ccb1cfc2aa7cee96d84d0b1cc3"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  gasLimit = 60000000
  operatorFeeScalar = 0
  operatorFeeConstant = 0
  chainFeesRecipient = "0x0000000000000000000000000000000000000000"
  minBaseFee = 0
  daFootprintGasScalar = 0
  [chains.roles]
    l1ProxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
    l2ProxyAdminOwner = "0x241f91e60ad685b4dd91450e153cc7396838132f"
    systemConfigOwner = "0x9998fdb851d3a3e793005e8eb5f10c0cc1f85399"
    unsafeBlockSigner = "0x919e6d1585db38f1e53316035b93fa9eb4b81746"
    batcher = "0x29ba3d997f0bf8b9a45ee1a3aba4dc1471efa470"
    proposer = "0x40aed6d9ef3d694aeb406d210db82613b67cf99d"
    challenger = "0xf6015e1850d6622921a647a76ffd892ba6870b75"
  [chains.deployOverrides]
    useRevenueShare = false
  [chains.customGasToken]
    liquidityControllerOwner = "0x0000000000000000000000000000000000000000"

[globalDeployOverrides]
  disputeGameFinalityDelaySeconds = 300
  l2GenesisJovianTimeOffset = "0x0"

